# chapter 4
#

SELECT address FROM publishers WHERE pub_id = '0877';
SELECT au_lname, au_fname FROM authors au_lname;
SELECT * FROM publishers;
SELECT pub_id, pub_name, address, city, state FROM publishers;
SELECT pub_id, pub_name FROM publishers;
SELECT pub_name, pub_id FROM publishers;
SELECT title_id, publishers.* FROM titles, publishers WHERE titles.pub_id=publishers.pub_id;
SELECT pub_name AS Publisher, pub_id FROM publishers;
SELECT title_id, ytd_sales * price - advance FROM titles;
SELECT title_id, (ytd_sales * price) - advance FROM titles;
SELECT title_id, ytd_sales * (price - advance) FROM titles;
SELECT p.pub_id, p.pub_name FROM publishers p;
SELECT publishers.pub_id, publishers.pub_name FROM publishers;

SELECT title, price FROM titles WHERE price > 15;
SELECT au_lname, au_fname FROM authors WHERE au_lname > 'McBadden';
SELECT title_id, price * 2 FROM titles WHERE advance > 10000;
SELECT au_id, phone FROM authors WHERE state <> 'CA';
SELECT au_id, phone, state FROM authors WHERE state <> 'CA';
SELECT * FROM authors WHERE au_lname = 'Ringer' AND au_fname = 'Anne';
SELECT au_id, au_lname, au_fname FROM authors WHERE au_fname = 'Anne' OR au_fname = 'Ann';
SELECT title, type, price, advance FROM titles WHERE price > 20 OR advance < 5000;
SELECT title, type, price, advance FROM titles WHERE type = 'business' OR price > 10 OR advance < 20000;
SELECT au_lname, au_fname FROM authors WHERE state <> 'CA';
SELECT au_lname, au_fname FROM authors WHERE NOT state = 'CA';
SELECT title_id, type, advance FROM titles WHERE type = 'business' OR type = 'psychology' AND advance > 5500;
SELECT title_id, type, advance FROM titles WHERE (type = 'business' OR type = 'psychology') AND advance > 5500;
SELECT title_id, type, price, advance, ytd_sales FROM titles WHERE price * ytd_sales < 2 * advance AND pubdate < '1985-10-15';
SELECT title_id, type, price, advance, ytd_sales, pubdate FROM titles WHERE price * ytd_sales < 2 * advance AND pubdate > '1985-10-15';
SELECT title_id, ytd_sales FROM titles WHERE ytd_sales BETWEEN 4095 and 12000;
SELECT title_id, ytd_sales FROM titles WHERE ytd_sales > 4095 and ytd_sales < 12000;
SELECT title_id, ytd_sales FROM titles WHERE ytd_sales NOT BETWEEN 4095 and 12000;
SELECT title_id, ytd_sales FROM titles WHERE ytd_sales < 4095 OR ytd_sales > 12000;
SELECT au_lname, state FROM authors WHERE state = 'CA' OR state = 'IN' OR state = 'MD';
SELECT au_lname, state FROM authors WHERE state IN ('CA', 'IN', 'MD');
SELECT au_lname, au_fname, phone FROM authors WHERE au_fname IN ('Meander', 'Malcolm', 'Stearns');
SELECT au_lname, state FROM authors WHERE au_id IN (SELECT au_id FROM titleauthors WHERE royaltyshare <.50);
SELECT au_lname, state FROM authors WHERE au_id NOT IN (SELECT au_id FROM titleauthors WHERE royaltyshare <.50);
SELECT title, advance FROM titles WHERE pub_id = '0877';
SELECT title_id, advance FROM titles WHERE advance < 5000;
SELECT title_id, advance FROM titles WHERE advance > 5000;
SELECT title_id, advance FROM titles WHERE advance IS NULL;
SELECT title_id, advance FROM titles WHERE advance < 5000 OR advance IS NULL; 
SELECT title_id, notes FROM titles WHERE notes LIKE '%xercise%';
SELECT au_lname, city FROM authors WHERE au_lname LIKE '_ars_n';
SELECT au_lname, au_fname, city FROM authors WHERE au_fname LIKE 'D__k';
SELECT au_lname, city FROM authors WHERE au_lname LIKE 'Mc%' OR au_lname LIKE 'Mac%';
SELECT au_lname, phone FROM authors WHERE phone LIKE '415%';
SELECT phone FROM authors WHERE phone NOT LIKE '415%';
SELECT phone FROM authors WHERE NOT phone LIKE '415%';
SELECT phone FROM authors WHERE phone = '415%';
SELECT title_id, notes FROM titles WHERE notes LIKE '%@%%' ESCAPE '@';
SELECT title_id, notes FROM titles WHERE notes LIKE '27%';
SELECT title_id, notes FROM titles WHERE notes LIKE '27@%';
SELECT title_id, notes FROM titles WHERE notes LIKE '_n';
SELECT title_id, notes FROM titles WHERE notes LIKE '@_n';
SELECT au_lname, au_fname, phone FROM authors WHERE au_fname LIKE '%ea%';
